name: discord_bot
description: '🤖 Discord bot used on Mineral Community'
version: 1.0.0
publish_to: none
authors:
 - Mineral Foundation

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
 path: ^1.8.0
 mineral: ^1.2.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
